import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import TextField from "@mui/material/TextField";
import Header from "../components/Header";
import DownloadPage from "../components/DownloadPage";

export default function Home() {
  return (
    <div className={styles.container} id="pagetodownload">
      <Header />
      <Head>
        <title>BMF ATTORNEYS-CONTRACT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.titles}>
        <h1>FIXED TERM AGREEMENT</h1>
        <p>Between</p>
      </div>
      <main className={styles.main}>
        <h2>BMF ATTORNEYS</h2>
        <h2>with company registration number 2022/123456/07</h2>
      </main>
      <div className={styles.titles}>
        <p>and</p>
      </div>
      <main className={styles.main}>
        <TextField
          id="standard-basic"
          variant="standard"
          label="[INSERT CLIENT NAME]"
          InputProps={{ style: { fontSize: 40 } }}
          InputLabelProps={{ style: { fontSize: 30 } }}
        />
      </main>
      <div className={styles.titles}>
        <p>Collectively referred herein as the “parties”</p>
      </div>
      <hr />
      <div className={styles.pagebody}>
        <ol>
          <li>
            <strong>Payment Terms:</strong>
          </li>
          <ul>
            <li>
              BMF Attorney’s fee &ensp;
              <span>
                <TextField
                  id="standard-basic"
                  variant="standard"
                  size="small"
                  InputProps={{ style: { fontSize: 20 } }}
                />
              </span>
              &ensp; (excluding VAT). The retainer fee can be paid upfront, or
              month-to-month and the payment terms can be payable as follows:
            </li>
            <li>Upfront:</li>
            <ul>
              <li>
                Three-twelfths of the fee during the probation period in 3 equal
                instalments by the 7th day of each month
              </li>
              <li>
                Nine-twelfths of the fee upon conclusion of the probation period
                of employment payable on the 7th day of the 4th month.
              </li>
            </ul>
            <li>Month-to-month:</li>
            <ul>
              <li>
                Three-twelfths of the fee during the probation period in 3 equal
                instalments by the 7th day of each month
              </li>
            </ul>
            <li>
              No variation or amendment to this Agreement shall be of any effect
              unless such amendment is put in writing and signed by all parties
            </li>
            <li>
              Any documentation prepared by <strong>BMF Attorneys </strong>
              remains its property
            </li>
          </ul>
          <div className={styles.counts}>
            <br />
            <li>
              <strong>Appointment </strong>
            </li>
            <ol>
              <li>
                The Client has procured the services of
                <strong> BMF Attorneys</strong> and hereby accepts the
                appointment as an independent contractor of the Client for a
                fixed period of time.
              </li>
              <li>
                The reason for this fixed-term contract is{" "}
                <strong>
                  for the appointment and completion of the &ensp;
                  <span>
                    <TextField
                      id="standard-basic"
                      variant="standard"
                      size="small"
                      InputProps={{ style: { fontSize: 20 } }}
                    />
                  </span>
                </strong>
                &ensp;
              </li>
            </ol>
          </div>
          <br />
          <li>
            <strong>Duration</strong>
          </li>
          <ol>
            <li>
              Notwithstanding the date of signature hereof, this fixed term
              contract shall be deemed to have commenced on the &ensp;
              <span>
                <TextField
                  id="standard-basic"
                  variant="standard"
                  size="small"
                  InputProps={{ style: { fontSize: 20 } }}
                />
              </span>
              &ensp; and will terminate, without further notice, on the &ensp;
              <span>
                <TextField
                  id="standard-basic"
                  variant="standard"
                  size="small"
                  InputProps={{ style: { fontSize: 20 } }}
                />
              </span>
              &ensp;.
              <br />
            </li>
            <li>
              The automatic termination of the contract on the Termination Date
              shall not be construed as a dismissal but as the completion of a
              fixed term contract.
            </li>
          </ol>
          <li></li>
        </ol>
      </div>
      <br />
      <div className={styles.signature}>
        <p>
          Signed at &ensp; ________________________________________ &ensp;
          on&ensp; _____________________________________&ensp;Who warrants
          authority on behalf of Jobox
        </p>
        <p>
          Signed at &ensp; ________________________________________ &ensp;
          on&ensp; _____________________________________&ensp;Who warrants
          authority on behalf of
        </p>
      </div>
      <br />
      <DownloadPage rootElementId="pagetodownload" DownloadFileName="Test" />
      <br />
      <footer className={styles.footer}></footer>
    </div>
  );
}
